### ISSUE TITLE
Transmission depth and subsurface radius don't have suggested bounds

### ISSUE THREAD

**Issue by virtualzavie** [AcademySoftwareFoundation/OpenPBR#108]
The valid range given for `transmission_depth` and `subsurface_radius` is $[0, \infty)$, which is impractical for UI. Is there a soft range we could suggest?

<img width="925" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenPBR/assets/9511025/d7991857-e001-4b06-ace6-98095bb5d629">

<img width="924" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenPBR/assets/9511025/adc06525-3626-4db9-8b05-a4b5dd860855">

**Comment by jstone-lucasfilm** [comment]
Thanks for this recommendation, @virtualzavie, as well as for the fix in #114.  I'll go ahead and mark this as resolved.
