### ISSUE TITLE
Clarify handling of rays incident to the surface from the interior

### ISSUE THREAD

**Issue by portsmouth** [AcademySoftwareFoundation/OpenPBR#110]
Currently we don't say much about how the model deals with the difference between rays exiting and entering the surface. This has to be handled in a renderer (at least one which tries to correctly render glass objects with a coat/fuzz, for example) so we should clarify this. 

For example consider the case of a glass object, with a coat and fuzz. Rays entering from the exterior (i.e. the ambient dielectric medium) will enter through the fuzz, then the coat, then transmit into the base glass.

Rays which hit the surface from the interior of the glass (having refracted into the glass at some earlier point in the path) instead hit the _bottom_ side of the coat, then the fuzz, then transmit into the ambient medium:

![image](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/2774364/830ba2d3-9fb0-408a-a497-171f028ad79a)

The physical effect of the layers differs in these case. For entering rays:

   - the fuzz reflection is un-tinted by the coat absorption
   - the coat reflection is dimmed and roughened by the fuzz
   - the dielectric reflection and transmission are both dimmed and roughened by both the coat and the fuzz

While for rays which are exiting:
   - the fuzz reflection (viewed from inside) now _will_ be tinted by the coat absorption
   - the reflection from the coat "top" interface (with the fuzz) is _not_ dimmed or roughened by the fuzz. This reflection is also an internal one, so has different Fresnel factor.  
   - only dielectric transmission is dimmed/roughened by coat and fuzz, while the reflection is unaffected (except for being an internal reflection as well)
   
However in Standard Surface (and MaterialX), we make no attempt to account for this in our albedo-scaling approximation of the layering. The Arnold implementation currently uses a rather crude approach where the normal is flipped so the surface always thinks the ray is entering 🤦‍♂️  (Then we have to use some messy logic to make nested dielectrics work despite this).

In reality there is kind of a symmetry between entering and exiting. In both cases the ray transmits from one external dielectric medium to another, via some intervening interfaces and layers of media, which we know. A sufficiently powerful layering formalism/system should be able to compute (within some reasonable approximation) the BSDF accounting correctly for this. It is possible to write down an albedo scaling approximation of this which looks symmetric, for example (which I didn't attempt in the spec). 

It is probably too much detail for us to elaborate on this in the spec (at least at this stage), but I think we should at least discuss what would need to be done to correctly model the physics. 

(Note, @iliyang and I discussed this issue previously in relation to Standard Surface).

**Comment by portsmouth** [comment]
I think the effects I described are implicit in the physical description, so we don't need to elaborate on them. Implementations typically won't bother modeling these, but in future renderers which e.g. do full MC light transport in the layer structure, they might attempt it.

I could perhaps add a couple sentences to spec noting that the entering/exiting rays encounter the layers in different order, which in principle should be accounted for in the layering math, but it isn't strictly necessary.

**Comment by peterkutz** [comment]
> A related issue is how we deal with rays which are exiting from the surface when the surface is locally (e.g.) a metal.
> 
> Arguably one can make sense of this by assuming the metal must be a thin sheet of foil covering the interior dielectric, so we would reflect from this foil back into the interior. This would allow for rendering of e.g. bottles with metallic labels, with the label visible through the glass (without the need for modelling a separate label).

This still seems like the best way to reason about the meaning of a mixture of metal and transmission to me. If the surface is being hit from the inside, then the bulk must have been transparent, so the metal must be a foil on top of the surface.
