### ISSUE TITLE
subsurface_radius_scale should maybe be a color (not a vector3)?

### ISSUE THREAD

**Issue by portsmouth** [AcademySoftwareFoundation/OpenPBR#144]
Currently we say that `subsurface_radius_scale` has type `vector3`.  But what does this mean operationally?  It's confusing for people doing UI, as to whether this parameter should have a color picker, but we certainly want it to. The components are in [0,1] range so there's no issue with the values.

Perhaps it just means that the parameter should not be color managed, but do we not want that, as the meaning of the RGB channels (i.e. which "curve" of wavelength bands a given radius should apply to)  should also change as the color space changes?  So i'm not sure it doesn't make more sense to just leave it as a color.

![image](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/2774364/bb77a82e-582a-476e-83bb-6d2c06345cf6)

**Comment by jstone-lucasfilm** [comment]
Thanks for posting this issue, @portsmouth, and this has been resolved in #220.
