### ISSUE TITLE
State white-furnace test behavior

### ISSUE THREAD

**Issue by portsmouth** [AcademySoftwareFoundation/OpenPBR#146]
The model as described [should](https://academysoftwarefdn.slack.com/archives/C06365EAQMP/p1699506650050319) pass a "white-furnace" test, in various configurations. This is because the model itself describes a physical structure (not a particular approximation) where the ground truth appearance is supposed to be the correct physical light transport through the structure thus defined.

So the ground truth appearance should perfectly preserve energy, assuming the parameters are configured so there is no physical energy dissipation/absorption. Configurations where this should happen, so a white-furnace test (i.e. test that the object should disappear when illuminated by uniform background light) would pass include:

 - metal base with white base and edge color.
  - dielectric base (with no specular tint, and no volume, or volume with a white albedo)
  - subsurface with a white albedo
  - diffuse with a white albedo
  - all of the above, plus an uncolored-coat
   - all of the above, plus white fuzz

It would be good to point this out in the spec, as these are obviously important unit test cases to verify for an implementation.

**Comment by portsmouth** [comment]
A short PR is needed to point this out in the spec.

**Comment by virtualzavie** [comment]
I think we can close this issue.
