### ISSUE TITLE
MaterialX reference implementation errors

### ISSUE THREAD

**Issue by JenusL** [AcademySoftwareFoundation/OpenPBR#148]
While trying out OpenPBR I noticed that there's some errors in the MaterialX reference implementation.
- `transmission_dispersion` should be removed.
- `transmission_dispersion_abbe_number` is missing.
- `transmission_dispersion_scale` is missing.
- `transmission_scatter_anisotropy` has `uimin` set to 0, this should be -1 so that it can allow for back scattering.

**Comment by portsmouth** [comment]
Fixed this up in https://github.com/AcademySoftwareFoundation/OpenPBR/pull/151.

**Comment by jstone-lucasfilm** [comment]
Thanks for posting this issue, @JenusL, and thanks to @portsmouth for the fix!
