### ISSUE TITLE
Thin film in micrometers divided by 2 for normalized parameter range

### ISSUE THREAD

**Issue by sharktacos** [AcademySoftwareFoundation/OpenPBR#150]
Currently thin film has a range of 0-2000 nanometers. I'd like to propose for discussion instead measuring in micrometers which would be 0-2 range, and then dividing that by 2 in order to have a normalized 0-1 parameter range. This makes a more artist friendly slider.

**Comment by portsmouth** [comment]
I like this, the existing requirement to input a length in nm seems a bit obscure to me.

**Comment by portsmouth** [comment]
Also, it's unclear from the spec how the `thin_film_ior` interacts with the IORs of the surrounding media. Should the thin-film disappear if its IOR equals the coat IOR for example? (Physically, presumably yes, but in implementations I've seen it currently doesn't).

**Comment by portsmouth** [comment]
A related proposal is to add a `thin_film_weight` parameter in [0,1], which will just blend the effect in and out. If we had that, keeping the width parameter in physical units might be more reasonable.

https://github.com/AcademySoftwareFoundation/OpenPBR/issues/134

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @sharktacos, and it's now addressed in #167.
