### ISSUE TITLE
Anisotropic roughness in MaterialX implemetation differs from the specification

### ISSUE THREAD

**Issue by msuzuki-nvidia** [AcademySoftwareFoundation/OpenPBR#153]
The .mtlx is utilizing the `<roughness_anisotropy>` from pbrlib, however the formula used in the function differs from the specification.
| <roughness_anisotropy> | Specification formula |
| -------- | -------- |
| ![mtlx_opbr_aluminum_brushed](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/153872239/0d4035aa-cc7b-4e01-bb98-c24134d27e41) | ![pt_opbr_aluminum_brushed](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/153872239/3cea6151-6835-4f78-bb6e-5e685773ea44) |

**Comment by jstone-lucasfilm** [comment]
That's a good note, thanks @msuzuki-nvidia, and we're planning to update this logic to match the current OpenPBR specification.
