### ISSUE TITLE
Oren-Nayar roughness parametrization is not sufficiently clear

### ISSUE THREAD

**Issue by portsmouth** [AcademySoftwareFoundation/OpenPBR#159]
We say:
![image](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/2774364/47c95812-0e2e-4592-991f-1a582f1f4872)

But the Oren-Nayar [model ](https://pbr-book.org/3ed-2018/Reflection_Models/Microfacet_Models#OrenndashNayarDiffuseReflection) actually involves a parameter $\sigma$ which parametrizes the roughness, and we don't say exactly how this is related to the roughness parameter in our model.

I suggest we follow the approach from Mitsuba [here](https://github.com/mitsuba-renderer/mitsuba/blob/10af06f365886c1b6dd8818e0a3841078a62f283/src/bsdfs/roughdiffuse.cpp#L134C1-L138C47):
```c++
        /* Conversion from Beckmann-style RMS roughness to
           Oren-Nayar-style slope-area variance. The factor
           of 1/sqrt(2) was found to be a perfect fit up
           to extreme roughness values (>.5), after which
           the match is not as good anymore */

        const Float conversionFactor = 1 / std::sqrt((Float) 2);

        Float sigma = m_alpha->eval(bRec.its).average()
            * conversionFactor;
```

So to be precise, we take 

$$ \sigma = r/\sqrt{2} $$

where $r$ is the `base_roughness` in $[0,1]$. This is the scheme used in Arnold for example. If there are no objections, we can just specify the same relationship in OpenPBR.

**Comment by jstone-lucasfilm** [comment]
Another good reference point for implementations of Oren-Nayar Diffuse is Open Shading Language, which is often followed by other shading languages when they need a standard reference.

Here's the language that we use to describe this in the various MaterialX implementations of Oren-Nayar Diffuse:

> Based on the OSL implementation of Oren-Nayar diffuse, which is in turn based on https://mimosa-pudica.net/improved-oren-nayar.html.

https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/libraries/pbrlib/genglsl/lib/mx_microfacet_diffuse.glsl#L3

**Comment by portsmouth** [comment]
Arnold uses the model from that blog post too, but with the mapping described, rather than the one from the blog post which is:

$$\sigma = \pi r \ .$$

With that mapping, we found:

>"The impact of this to the user is that only the portion diffuse_roughness in [0, 0.2] corresponds to a realistic Beckmann surface. For 80% of the parameter range, the model basically produces a nonlinear change in brightness that doesn't correspond to the underlying physics of the spiky surface and doesn't really buy the user anything but an unwanted change in diffuse color they need to correct for."

Hence the switch to $\sigma = r/\sqrt{2}$.

It seems like some more investigation is needed here to verify the best mapping. Also, I'm a bit uncomfortable using a non-peer-reviewed blog post as the source for the model (OK in an internal implementation perhaps, but not in a public specification), even though the results might be good. Maybe there is something equivalent in the published literature?

**Comment by jstone-lucasfilm** [comment]
Here's the way that Open Shading Language references the blog post, with a clarification about which of the two implementations in the post is used:

// Simplified math from: "A tiny improvement of Oren-Nayar reflectance model"
// by Yasuhiro Fujii
// http://mimosa-pudica.net/improved-oren-nayar.html
// NOTE: This is using the math to match the original ON model, not the tweak
// proposed in the text which is a slightly different BRDF

https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/blob/35820fc99b3ad285308ce3ad0389ef84469ce929/src/testrender/shading.cpp#L472

So far, I'm not aware of any more formal way to reference this implementation, but I'd love to hear from others if they know one.

**Comment by Sam-Izdat** [comment]
Just a few pertinent slides re. Oren-Nayar and its roughness parameter `s` vs. GGX+Smith and its `α` from Earl Hammon, Jr. in [PBR Diffuse Lighting for GGX+Smith Microsurfaces](https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc2017/Presentations/Hammon_Earl_PBR_Diffuse_Lighting.pdf)

![image](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/2222161/ed299b23-348e-4259-8572-323c39f350be)
![image](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/2222161/a471db00-16d7-4bed-8cee-fc5773751225)

Is it out of the question at this point to consider alternative diffuse models that would mesh naturally with GGX?

**Comment by portsmouth** [comment]
>Is it out of the question at this point to consider alternative diffuse models that would mesh naturally with GGX?

Indeed, we're discussing some such alternative models on Slack, with Eugene d'Eon. (His model is based on a generalization of Smith model beyond heightfield to a model of a "porous" medium with 3d structure, as far I understand).

From my point of view, the traditional Oren-Nayar model is not bad visually (and fairly simple and efficient, which is a plus), though it does suffer from some subtle artifacts and not-so-subtle darkening, both of which can be fixed though with some simple modifications (e.g. building on model of Fujii mentioned above).
