### ISSUE TITLE
Visual discontinuity at `transmission_depth` of zero

### ISSUE THREAD

**Issue by jstone-lucasfilm** [AcademySoftwareFoundation/OpenPBR#179]
I'm not yet sure of the cause of this visual discontinuity, whether it's in the MaterialX graph for OpenPBR or perhaps in the real-time approximation of the MaterialX Physically Based Shading nodes, so I wanted to report it here for discussion.

When `transmission_depth` is exactly zero, the `transmission_color` input has an intuitive visual effect in real-time OpenPBR renders, but this effect disappears entirely when `transmission_depth` is set to any non-zero value, creating a visual discontinuity as the artist moves the slider.

This issue can be seen most easily in the `open_pbr_honey.mtlx` example material, linked here:
https://academysoftwarefoundation.github.io/MaterialX/?file=Materials/Examples/OpenPbr/open_pbr_honey.mtlx

If you open the Property Editor and set `transmission_depth` to exactly zero, then the honey color of the transmission component becomes visible, but it disappears again when `transmission_depth` is set to a value slightly above zero.

OpenPBR Honey (zero transmission depth):
![image](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/6146549/dc0a4e48-28d5-478a-88fb-481dced7c54d)

OpenPBR Honey (epsilon transmission depth)
![image](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/6146549/d63f7c01-7a4c-4986-8960-1c228d9b3218)

**Comment by virtualzavie** [comment]
I believe this is the intended behaviour, where `transmission_depth` == 0 is a special case where the `transmission_color` is used as a simple multiplier, whereas any other value is the depth at which the `transmission_color` happens.

Quoting the parameter description:
> Controls the depth into the volume at which the `transmission_color` is realized; if zero, acts as a constant (on-surface) transmission tint.

**Comment by jstone-lucasfilm** [comment]
That's great additional context, thanks @virtualzavie.

Does this mean that renderers will require support for volumetric rendering techniques (i.e. absorption and scattering) in order to correctly handle examples such as `open_pbr_honey.mtlx`?

We can certainly add approximations of these techniques to our MaterialX GLSL/ESSL/MSL codebase, but this is a higher bar than Autodesk Standard Surface set for real-time renderers, since its corresponding `transmission_depth` term was simply ignored in non-volumetric renderers.

**Comment by jstone-lucasfilm** [comment]
This may end up becoming a feature request for the MaterialX codebase, since ultimately we need to add simple approximations of absorption and scattering in GLSL/ESSL/MSL, but I'll keep this GitHub Issue open to gather thoughts from Jamie and Peter as well.

**Comment by portsmouth** [comment]
Yes this discontinuity exists in Standard Surface as well, and was inherited into OpenPBR.

We say:
>The `transmission_depth` is the distance traveled inside the medium by white light before its color becomes exactly `transmission_color` by Beer's law .... However when `transmission_depth` is zero, it is assumed that the interior medium is absent ... and `transmission_color` is used instead to non-physically tint the dielectric refraction Fresnel factor multiplicatively by a constant amount (ignoring the dielectric energy balance).

So zero transmission depth produces the tinting behavior, whereas as the depth $\epsilon$ is increased away from zero, the medium starts extremely dense (infinite in the $\epsilon \rightarrow 0$ limit..) and gets progressively less dense.

We noted early on that this is rather unintuitive, and suggested to replace the depth with a density (as is more traditional for volumes), e.g. in https://github.com/AcademySoftwareFoundation/OpenPBR/issues/71. But it seemed hard to get a consensus about this.

**Comment by portsmouth** [comment]
In summary, the discontinuity you see in the viewer is due to a) inherent discontinuity in our parametrization (by design), and b) that the viewer has not implemented volumes. Is there more to discuss?

**Comment by jstone-lucasfilm** [comment]
I'd agree that this is resolved, thanks @portsmouth, and I'll mark the issue as closed.
