### ISSUE TITLE
Implementing thin-film interference in combination with F82-tint metallic Fresnel

### ISSUE THREAD

**Issue by lukasstockner** [AcademySoftwareFoundation/OpenPBR#79]
The current spec draft points out [the method used for implementing thin-film interference effects](https://belcour.github.io/blog/research/publication/2017/05/01/brdf-thin-film.html). However, this paper and its reference implementation assume that the physically correct dielectric and conductive Fresnel terms are used so that the optical phase shift can be computed.

However, OpenPBR uses the F82-tint model for metals, which directly computes the reflectivity without going through computing a complex IOR and then using it in the conductive Fresnel term.

Therefore, it might be helpful to include a note in the spec on how to reconcile this and how to compute/estimate the phase shift when implementing the thin-film component.

**Comment by portsmouth** [comment]
We need a PR to clarify the thin film behavior.

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @lukasstockner, and it's now addressed in #167.
