### ISSUE TITLE
Define unspecified BSDFs

### ISSUE THREAD

**Issue by anderslanglands** [AcademySoftwareFoundation/OpenPBR#84]
Currently diffuse and fuzz bsdfs are unspecificied. From our point of view, these would be much better explicitly specified as not doing so will necessarily lead to look differences between implementations.

**Comment by jstone-lucasfilm** [comment]
Thanks for these key recommendations, @anderslanglands, and I believe these issues are now resolved in the main branch of OpenPBR.
